set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
"Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
"Plugin 'L9'
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Avoid a name conflict with L9
"Plugin 'user/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

Plugin 'altercation/vim-colors-solarized'  " New line!!
Plugin 'matrix.vim--Yang'
Plugin 'jiangmiao/auto-pairs'
Plugin 'tpope/vim-surround'

" Haskell
Plugin 'dag/vim2hs'

" markdown
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'vim-pandoc/vim-pandoc'
Plugin 'vim-pandoc/vim-pandoc-syntax'

" terryma/vim-multiple-cursors
Plugin 'terryma/vim-multiple-cursors'

" Python folding
Plugin 'tmhedberg/SimpylFold'

Plugin 'Valloric/YouCompleteMe'
let g:ycm_path_to_python_interpreter = '/usr/bin/python'
" let g:ycm_path_to_python_interpreter = '/Users/billryan/.pyenv/versions/anaconda-2.1.0/bin/python'
let g:ycm_server_keep_logfiles = 1
let g:ycm_server_log_level = 'debug'

" scrooloose/syntastic
Plugin 'scrooloose/syntastic'

" configurations for syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_python_checkers = ['pep8']
let g:syntastic_mode_map = { 'passive_filetypes': ['rst', 'md', 'tex']  }

set fencs=utf-8,gbk

" Some settings to enable the theme:
set number        " Show line numbers
set colorcolumn=80
syntax enable     " Use syntax highlighting
set background=dark
colorscheme solarized

" folding
set foldmethod=syntax
set foldnestmax=2
nnoremap <space> za
vnoremap <space> zf

